# Generated by Django 5.2.8 on 2026-01-06 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('candidato', 'Candidato'), ('empresa', 'Empresa'), ('admin', 'Administrador')], default='admin', max_length=10),
        ),
    ]
