# Generated by Django 5.2.8 on 2026-01-26 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('cpf', models.CharField(db_index=True, max_length=11, unique=True)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
