# Generated by Django 5.2.8 on 2025-12-23 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='cpf',
            field=models.CharField(db_index=True, max_length=11, unique=True),
        ),
    ]
