# Generated by Django 5.2.10 on 2026-01-28 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='candidatos/perfil/'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='sobre',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='cpf',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.CreateModel(
            name='ExperienciaProfissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=150)),
                ('empresa', models.CharField(max_length=150)),
                ('inicio', models.IntegerField()),
                ('fim', models.IntegerField(blank=True, null=True)),
                ('descricao', models.TextField()),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiencias', to='candidato.candidato')),
            ],
        ),
        migrations.CreateModel(
            name='FormacaoAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(max_length=150)),
                ('instituicao', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formacoes', to='candidato.candidato')),
            ],
        ),
    ]
