# Generated by Django 5.2.8 on 2026-01-28 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='candidato',
            name='experiencia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidato',
            name='formacao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidato',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='candidatos/'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
