# Generated by Django 5.2.8 on 2025-12-30 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=200)),
                ('cnpj', models.CharField(db_index=True, max_length=14, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('quantidade', models.PositiveBigIntegerField(default=1)),
                ('requisitos', models.TextField()),
                ('modelo_trabalho', models.CharField(choices=[('presencial', 'Presencial'), ('remoto', 'Remoto'), ('hibrido', 'Híbrido')], max_length=20)),
                ('tipo_contrato', models.CharField(choices=[('clt', 'CLT'), ('pj', 'PJ'), ('temporario', 'Temporário')], max_length=20)),
                ('jornada', models.CharField(max_length=50)),
                ('faixa_salarial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vale_refeicao', models.BooleanField(default=False)),
                ('plano_saude', models.BooleanField(default=False)),
                ('vale_transporte', models.BooleanField(default=False)),
                ('outros_beneficios', models.BooleanField(default=False)),
                ('diferencial', models.CharField(blank=True, max_length=255, null=True)),
                ('descricao', models.TextField()),
                ('ativa', models.BooleanField(default=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vagas', to='empresa.empresa')),
            ],
        ),
    ]
