# Generated by Django 5.2.8 on 2026-01-26 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidato', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=200)),
                ('cnpj', models.CharField(db_index=True, max_length=14, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('instagram', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=50, null=True)),
                ('cidade', models.CharField(blank=True, max_length=50, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('complemento', models.CharField(blank=True, max_length=255, null=True)),
                ('sobre', models.TextField(blank=True, null=True)),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='empresas/perfil/')),
                ('capa', models.ImageField(blank=True, null=True, upload_to='empresas/perfil/')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('quantidade', models.PositiveBigIntegerField(default=1)),
                ('requisitos', models.TextField()),
                ('modelo_trabalho', models.CharField(choices=[('presencial', 'Presencial'), ('remoto', 'Remoto'), ('hibrido', 'Híbrido')], max_length=20)),
                ('tipo_contrato', models.CharField(choices=[('clt', 'CLT'), ('pj', 'PJ'), ('temporario', 'Temporário')], max_length=20)),
                ('jornada', models.CharField(max_length=50)),
                ('faixa_salarial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vale_refeicao', models.BooleanField(default=False)),
                ('plano_saude', models.BooleanField(default=False)),
                ('vale_transporte', models.BooleanField(default=False)),
                ('outros_beneficios', models.BooleanField(default=False)),
                ('diferencial', models.CharField(blank=True, max_length=255, null=True)),
                ('descricao', models.TextField()),
                ('tipo', models.CharField(choices=[('emprego', 'Emprego'), ('estagio', 'Estágio')], max_length=10)),
                ('ativa', models.BooleanField(default=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vagas', to='empresa.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Candidatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inscricao', models.DateTimeField(auto_now_add=True)),
                ('curriculo', models.FileField(blank=True, null=True, upload_to='curriculos/')),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidaturas', to='candidato.candidato')),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidaturas', to='empresa.vaga')),
            ],
        ),
    ]
