# Generated by Django 5.2.8 on 2025-12-23 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='cnpj',
            field=models.CharField(db_index=True, max_length=14, unique=True),
        ),
    ]
