# Generated by Django 5.2.8 on 2026-01-05 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaga',
            name='tipo',
            field=models.CharField(choices=[('emprego', 'Emprego'), ('estagio', 'Estágio')], default='emprego', max_length=10),
            preserve_default=False,
        ),
    ]
