# Generated by Django 5.2.8 on 2026-01-12 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_vaga_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='empresa/perfil/'),
        ),
    ]
