# Generated by Django 5.2.8 on 2026-01-22 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0005_empresa_bairro_empresa_cidade_empresa_complemento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='capa',
            field=models.ImageField(blank=True, null=True, upload_to='empresas/capas/'),
        ),
    ]
